import type { Manifest } from '../../types.ts';
import type { TrackerIndex, TrackerSheet, TrackerStock } from '../tracker.ts';
import type { IntradayResearch } from '../intraday/evaluate.ts';
import type { PortfolioReport } from '../portfolio.ts';
import type { LongHistoryFile, PriceSummary } from '../prices.ts';
import type { ResearchReport, ResearchScores } from '../research/research.ts';
import type { SameDaySummary } from '../tests/sameDay.ts';
import type { StockListFile } from './stockList.ts';
import { fileId } from './symbols.ts';

/** Files generated by the daily GitHub Action (or `npm run fetch-data` / `build-tracker` locally). */
async function getJson<T>(path: string, signal?: AbortSignal): Promise<T | null> {
  // The daily update replaces these files; revalidating (cheap, via ETag) avoids showing a stale copy after a deploy.
  const res = await fetch(`${import.meta.env.BASE_URL}${path}`, { signal, cache: 'no-cache' });
  const isJson = res.headers.get('content-type')?.includes('json') ?? false;
  return res.ok && isJson ? ((await res.json()) as T) : null;
}

export const loadResearchReport = (signal?: AbortSignal) => getJson<ResearchReport>('research/report.json', signal);
export const loadResearchScores = (signal?: AbortSignal) => getJson<ResearchScores>('research/scores.json', signal);
export const loadIntradayResearch = (signal?: AbortSignal) => getJson<IntradayResearch>('research/intraday.json', signal);
export const loadSameDaySummary =(signal?: AbortSignal) => getJson<SameDaySummary>('research/same-day.json', signal);
export const loadPortfolios =(signal?: AbortSignal) => getJson<PortfolioReport>('tracker/portfolios.json', signal);
export const loadStockList =(signal?: AbortSignal) => getJson<StockListFile>('data/nse-stocks.json', signal);
export const loadManifest =(signal?: AbortSignal) => getJson<Manifest>('data/index.json', signal);
export const loadPriceSummary = (signal?: AbortSignal) => getJson<PriceSummary>('data/prices.json', signal);
/** Only stocks with more than 10 years of prices in the daily update have one. */
export const loadLongHistory = (symbol: string, signal?: AbortSignal) => getJson<LongHistoryFile>(`data/long/${fileId(symbol)}.json`, signal);
export const loadTrackerIndex = (signal?: AbortSignal) => getJson<TrackerIndex>('tracker/index.json', signal);
export const loadTrackerStock = (symbol: string, signal?: AbortSignal) =>
  getJson<TrackerStock>(`tracker/stocks/${fileId(symbol)}.json`, signal);
export const loadTrackerSheet = (date: string, signal?: AbortSignal) => getJson<TrackerSheet>(`tracker/sheets/${date}.json`, signal);
