import type { Manifest } from '../../types.ts';
import type { TrackerIndex, TrackerSheet, TrackerStock } from '../tracker.ts';
import { fileId } from './symbols.ts';

/** Files generated by the daily GitHub Action (or `npm run fetch-data` / `build-tracker` locally). */
async function getJson<T>(path: string, signal?: AbortSignal): Promise<T | null> {
  const res = await fetch(`${import.meta.env.BASE_URL}${path}`, { signal });
  const isJson = res.headers.get('content-type')?.includes('json') ?? false;
  return res.ok && isJson ? ((await res.json()) as T) : null;
}

export const loadManifest = (signal?: AbortSignal) => getJson<Manifest>('data/index.json', signal);
export const loadTrackerIndex = (signal?: AbortSignal) => getJson<TrackerIndex>('tracker/index.json', signal);
export const loadTrackerStock = (symbol: string, signal?: AbortSignal) =>
  getJson<TrackerStock>(`tracker/stocks/${fileId(symbol)}.json`, signal);
export const loadTrackerSheet = (date: string, signal?: AbortSignal) => getJson<TrackerSheet>(`tracker/sheets/${date}.json`, signal);
